apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nursing-platform
resources:
  - alerts.yaml
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - otel-collector-config.yaml
  - otel-collector.yaml
  - servicemonitor.yaml
  - migrations.yaml
  - workers.yaml
  - edge.yaml
  - core-domain.yaml
  - extended-domain.yaml
  - hpa.yaml
  - ingress.yaml