apiVersion: v1
kind: Namespace
metadata:
  name: nursing-platform
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/name: nursing-platform
    app.kubernetes.io/part-of: nursing-backend-services