apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nursing-otel-collector
  labels:
    app.kubernetes.io/part-of: nursing-platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otel-collector
  endpoints:
    - port: prom-metrics
      interval: 30s
      path: /