// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NursingBackend.Services.Staffing;

#nullable disable

namespace NursingBackend.Services.Staffing.Migrations
{
    [DbContext(typeof(StaffingDbContext))]
    [Migration("20260417062303_InitialStaffingSchema")]
    partial class InitialStaffingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NursingBackend.BuildingBlocks.Entities.StaffMemberEntity", b =>
                {
                    b.Property<string>("StaffId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<int>("Attendance")
                        .HasColumnType("integer");

                    b.Property<string>("Bonus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CertificatesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EmploymentSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HireDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OnboardingNote")
                        .HasColumnType("text");

                    b.Property<string>("PartnerAffiliationRole")
                        .HasColumnType("text");

                    b.Property<string>("PartnerAgencyId")
                        .HasColumnType("text");

                    b.Property<string>("PartnerAgencyName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Performance")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Satisfaction")
                        .HasColumnType("integer");

                    b.Property<string>("ScheduleJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StaffId");

                    b.HasIndex("TenantId", "Department", "Status", "LifecycleStatus", "CreatedAtUtc");

                    b.ToTable("StaffMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
