// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NursingBackend.Services.Elder;

#nullable disable

namespace NursingBackend.Services.Elder.Migrations
{
    [DbContext(typeof(ElderDbContext))]
    [Migration("20260417020247_AddAssessmentCaseFields")]
    partial class AddAssessmentCaseFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NursingBackend.BuildingBlocks.Entities.AdmissionRecordEntity", b =>
                {
                    b.Property<string>("AdmissionId")
                        .HasColumnType("text");

                    b.Property<int>("AdlScore")
                        .HasColumnType("integer");

                    b.Property<string>("AdmissionReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AiAssessmentScore")
                        .HasColumnType("integer");

                    b.Property<int>("AiConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("AiFocusTags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiPlanTemplateCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiReasonSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiReasons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiRecommendedCareLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AllergySummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssessmentStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CareLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChronicConditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CognitiveLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConfirmedBy")
                        .HasColumnType("text");

                    b.Property<string>("ConfirmedCareLevel")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MedicationSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedCareLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<string>("RiskNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceDocumentNames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceLabel")
                        .HasColumnType("text");

                    b.Property<string>("SourceSummary")
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AdmissionId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("NursingBackend.BuildingBlocks.Entities.ElderProfileEntity", b =>
                {
                    b.Property<string>("ElderId")
                        .HasColumnType("text");

                    b.Property<int?>("AdlScore")
                        .HasColumnType("integer");

                    b.Property<string>("AdmissionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("BirthDate")
                        .HasColumnType("text");

                    b.Property<string>("CareLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CognitiveLevel")
                        .HasColumnType("text");

                    b.Property<string>("ElderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ElderPhone")
                        .HasColumnType("text");

                    b.Property<string>("EntrustmentOrganization")
                        .HasColumnType("text");

                    b.Property<string>("EntrustmentType")
                        .HasColumnType("text");

                    b.Property<string>("FamilyContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FamilyContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityCard")
                        .HasColumnType("text");

                    b.Property<string>("MedicalAlerts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("MonthlySubsidy")
                        .HasColumnType("numeric");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceItems")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceNotes")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ElderId");

                    b.ToTable("Elders");
                });

            modelBuilder.Entity("NursingBackend.BuildingBlocks.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<string>("OutboxMessageId")
                        .HasColumnType("text");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OutboxMessageId");

                    b.ToTable("OutboxMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
