// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NursingBackend.Services.Operations;

#nullable disable

namespace NursingBackend.Services.Operations.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    partial class OperationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NursingBackend.BuildingBlocks.Entities.AlertCaseEntity", b =>
                {
                    b.Property<string>("AlertId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<string>("ElderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ElderlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("HandledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HandledBy")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AlertId");

                    b.HasIndex("TenantId", "Module", "Status", "Level", "OccurredAtUtc");

                    b.ToTable("AlertCases");
                });
#pragma warning restore 612, 618
        }
    }
}
