apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nursing-api-gateway
spec:
  minReplicas: 2
  maxReplicas: 4
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nursing-admin-bff
spec:
  minReplicas: 2
  maxReplicas: 4
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nursing-family-bff
spec:
  minReplicas: 2
  maxReplicas: 4
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nursing-nani-bff
spec:
  minReplicas: 2
  maxReplicas: 4