// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NursingBackend.Services.Care;

#nullable disable

namespace NursingBackend.Services.Care.Migrations
{
    [DbContext(typeof(CareDbContext))]
    [Migration("20260402115725_AddCareWorkflowRealization")]
    partial class AddCareWorkflowRealization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NursingBackend.BuildingBlocks.Entities.CarePlanEntity", b =>
                {
                    b.Property<string>("CarePlanId")
                        .HasColumnType("text");

                    b.Property<string>("ElderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ElderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CarePlanId");

                    b.ToTable("CarePlans");
                });

            modelBuilder.Entity("NursingBackend.BuildingBlocks.Entities.CareTaskEntity", b =>
                {
                    b.Property<string>("TaskId")
                        .HasColumnType("text");

                    b.Property<string>("AssigneeRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DueAtLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ElderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaskId");

                    b.ToTable("CareTasks");
                });

            modelBuilder.Entity("NursingBackend.BuildingBlocks.Entities.CareWorkflowAuditEntity", b =>
                {
                    b.Property<string>("AuditId")
                        .HasColumnType("text");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailJson")
                        .HasColumnType("text");

                    b.Property<string>("OperatorUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatorUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AuditId");

                    b.HasIndex("TenantId", "AggregateType", "AggregateId");

                    b.ToTable("CareWorkflowAudits");
                });

            modelBuilder.Entity("NursingBackend.BuildingBlocks.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<string>("OutboxMessageId")
                        .HasColumnType("text");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OutboxMessageId");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("NursingBackend.BuildingBlocks.Entities.ServicePackageEntity", b =>
                {
                    b.Property<string>("PackageId")
                        .HasColumnType("text");

                    b.Property<string>("AddOnsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BoundElders")
                        .HasColumnType("integer");

                    b.Property<string>("CareLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MonthlyPrice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PricingNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceScopeJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettlementCycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PackageId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("ServicePackages");
                });

            modelBuilder.Entity("NursingBackend.BuildingBlocks.Entities.ServicePlanAssignmentEntity", b =>
                {
                    b.Property<string>("AssignmentId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DayLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ElderlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmploymentSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartnerAgencyName")
                        .HasColumnType("text");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StaffRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AssignmentId");

                    b.HasIndex("TenantId", "DayLabel", "StaffName");

                    b.ToTable("ServicePlanAssignments");
                });

            modelBuilder.Entity("NursingBackend.BuildingBlocks.Entities.ServicePlanEntity", b =>
                {
                    b.Property<string>("PlanId")
                        .HasColumnType("text");

                    b.Property<string>("CareLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElderlyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<string>("RiskTagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShiftSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlanId");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("ServicePlans");
                });

            modelBuilder.Entity("NursingBackend.BuildingBlocks.Entities.ServicePlanTaskExecutionEntity", b =>
                {
                    b.Property<string>("TaskExecutionId")
                        .HasColumnType("text");

                    b.Property<string>("ActionNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("HandledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HandledBy")
                        .HasColumnType("text");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TaskExecutionId");

                    b.HasIndex("TenantId", "PlanId");

                    b.ToTable("ServicePlanTaskExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
