apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nursing-platform-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nursing-platform-cluster-secrets
  target:
    name: nursing-platform-secrets
    creationPolicy: Owner
  data:
    - secretKey: Jwt__SigningKey
      remoteRef:
        key: prod/nursing-platform/backend
        property: jwtSigningKey
    - secretKey: ConnectionStrings__Postgres
      remoteRef:
        key: prod/nursing-platform/backend
        property: postgresConnectionString
    - secretKey: RabbitMq__Password
      remoteRef:
        key: prod/nursing-platform/backend
        property: rabbitMqPassword