apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nursing-api-gateway
spec:
  minReplicas: 3
  maxReplicas: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nursing-admin-bff
spec:
  minReplicas: 3
  maxReplicas: 8
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nursing-family-bff
spec:
  minReplicas: 3
  maxReplicas: 8
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nursing-nani-bff
spec:
  minReplicas: 3
  maxReplicas: 8
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nursing-care
spec:
  minReplicas: 3
  maxReplicas: 12
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nursing-notification
spec:
  minReplicas: 3
  maxReplicas: 12