apiVersion: apps/v1
kind: Deployment
metadata:
  name: nursing-api-gateway
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nursing-admin-bff
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nursing-family-bff
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nursing-nani-bff
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nursing-identity
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nursing-tenant
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nursing-elder
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nursing-care
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nursing-health
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nursing-visit
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nursing-notification
spec:
  replicas: 1